name: License Compliance Acknowledgment

description: You must confirm you understand the Comprehensive Minority Protection Clause.

body:
  - type: markdown
    attributes:
      value: |
        ### ⚠️ License Notice

        By opening an issue, you acknowledge:

        - This project uses AGPL v3 + a Universal Comprehensive Minority Protection Clause.

        - Institutional, financial, and operational use is strictly conditional.

        - Institutions must protect ALL minorities comprehensively (cannot cherry-pick protections).

        - Commercial finance and profit-seeking use are prohibited.

  - type: checkboxes
    attributes:
      label: Confirm
      description: You must agree to proceed.
      options:
        - label: I understand that this project forbids commercial/profit-seeking financial use.
        - label: I understand that institutional use requires comprehensive protection of ALL marginalized groups.
        - label: I understand that institutions cannot cherry-pick protections (must protect all minorities).
        - label: I agree not to use this project in any way that harms ANY marginalized people.



